[package]
name = "grower-jsni"
edition.workspace = true
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4.45"
